### ISSUE TITLE
Enhancement: why not as a C++ module using Pool/PackedFloatVector?

### ISSUE THREAD

**Issue by Vivraan** [higgs-bosoff/godot-linalg#1]

**Comment by higgs-bosoff** [comment]
Because I have no experience making those, unfortunately. I realise it would be better, especially performance-wise, but I've never tried and when I did this I just wanted something that worked for my purposes. Feel free to fork though if you have an idea and are willing to try it!

**Comment by Vivraan** [comment]
No promises, but it'll be an amazing exercise for me in gdnative.

**Comment by higgs-bosoff** [comment]
Looking forward to it! If I manage to understand how it's configured and get it working, then I can contribute too, and that that point it might become possible to incorporate more sophisticated algorithms. I can code in C++, just inexperienced with the Godot bindings.
